# -*- coding: utf-8 -*-
"""Currency_Converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWmisbS7RXRM_W-AAKiST0KIjhfczWuR
"""

import numpy as np
from bs4 import BeautifulSoup
import requests
import pandas_datareader as web
import datetime as dt

from_currency = input("Enter currency you wish to convert from: ")
to_currency = input("Enter currency you wish to convert to: ")
amount = input('Enter amount you wish to convert: ')

company = f'{from_currency}{to_currency}=X'
start = dt.datetime(2021, 3, 21)
end = dt.date.today()
today = dt.date.today()
yesterday = today - dt.timedelta(days=1)
data = web.DataReader(company, 'yahoo', yesterday, today)['Close']
amount = float(amount)
exchange = float(data[0])
to_amount = exchange*amount
print(f'{amount} {from_currency} = {to_amount} {to_currency}')